export const EstatusBitacoraConsts = {
  ALTA_FOLIO: 'Alta folio',
  PENDIENTE_DE_DOCUMENTACION: 'Pendiente de documentación',
  FORMATOS_ENVIADOS_A_ASEGURADORA: 'Formatos enviados a aseguradora',
  EN_ESPERA_DE_FIRMA_EJECUTIVO: 'En espera de firma ejecutivo',
  EN_PROCESO_DE_GESTION: 'En proceso de gestión',
  GENERACION_DE_FORMATOS:'Generación de formatos',
  FALTA_DE_INFORMACION: 'Falta de información',
  FORMATOS_GENERADOS:'Formatos generados',
  EN_ESPERA_FIRMA: 'En espera firma',
  FISICOS_ENVIADOS:'Físicos enviados',
  DATOS_DE_CONTACTO_INCORRECTOS:'Datos de contacto incorrectos',
  FORMATOS_ENVIADOS_A_AFIANZADORA:'Formatos enviados a afianzadora',
  CORRECION_DE_FORMATOS:'Correcion de formatos',
  EN_ESPERA_DE_FIRMA_ASEGURADO:'En espera de firma asegurado',
  RECOLECCION_DE_FISICOS:'Recolección de físicos',
  GESTIONADO:'Gestionado',
  EN_VALIDACION_DE_FIRMAS: 'En validación de firmas',
  EN_VALIDACION_DOCUMENTAL: 'En validación documental'
};
